import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GameProvider from "@/providers/GameProvider";
import ToastContainer from "@/components/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Burdaerata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <GameProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-br from-indigo-50/20 to-violet-100/20`}
          >
            <header className="sticky top-0 z-50 flex justify-between items-center p-4 gap-4 h-16 md:h-10 bg-[#6c47ff] shadow-sm">
              <h1 className="text-3xl md:text-xl font-bold text-white my-2 text-start">
                Burdaerata
              </h1>
              <div className="items-end  flex gap-2">
                <SignedOut>
                  <SignInButton>
                    <button className="text-[#6c47ff] bg-white rounded-full font-medium text-sm h-8 px-4 md:px-2 hover:bg-white/90 transition-colors">
                      Sign In
                    </button>
                  </SignInButton>
                  <SignUpButton>
                    <button className="bg-white text-[#6c47ff] rounded-full font-medium text-sm h-8 px-4 md:px-2 hover:bg-white/90 transition-colors">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton
                    appearance={{ variables: { colorPrimary: "#6c47ff" } }}
                  />
                </SignedIn>
              </div>
            </header>
            <main className="flex-1 container max-w-full mx-auto bg-[#99184e] pt-8 min-h-dvh">
              {children}
            </main>
            <ToastContainer />
          </body>
        </html>
      </GameProvider>
    </ClerkProvider>
  );
}
