import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import GameProvider from '@/providers/GameProvider';
import ClerkApiProvider from '@/providers/ClerkApiProvider';
import { Toaster } from '@/components/ui/sonner';
import Header from '@/components/header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Burdaerata',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ClerkApiProvider>
        <GameProvider>
          <html lang='en' className='h-full'>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-br from-indigo-50/20 to-violet-100/20 h-full flex flex-col`}
            >
              <Header />
              <main className='flex-1 flex flex-col overflow-auto'>
                <div className='container max-w-full mx-auto flex-1'>
                  {children}
                </div>
              </main>
              <Toaster />
            </body>
          </html>
        </GameProvider>
      </ClerkApiProvider>
    </ClerkProvider>
  );
}
